### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by BennyKJohnson** [Podcastindex-org/aggregator#9]
Hello,

Last night I had a bit of a look at the aggregator script.
I noticed that there are currently hardcoded paths in the script with the intention that these should be replaced by the dev. For example `path/to/config/global.conf`. These paths can make it difficult to get up and running and also contribute changes as they have to be reverted back to their original state. I have some thoughts on how to improve this.

 For the global config location: 
- Provide a CLI argument for the config location `node Aggrivate.js --config ./global.conf'
- Use a env variable to set the config path. This would look something like `CONFIG_PATH=./global.conf node aggrivate.js`

The remained on the hardcoded paths could come from the global config.
Happy to put up a PR for this, just wanted to get your thoughts @daveajones.

Thank you

**Comment by daveajones** [comment]
I need to update this code so that we’re all looking at the most current version. Some things have changed with it over the time since I first posted it. I’ll do that soon.

If you want to change some things and do a PR that’ll be fine. I’ll just incorporate those changes, where appropriate, into the new code before posting.

**Comment by BennyKJohnson** [comment]
This has been resolved with https://github.com/Podcastindex-org/aggregator/pull/11 and https://github.com/Podcastindex-org/aggregator/pull/12
